# Generated by Django 5.2.7 on 2025-10-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_movie_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
