# Generated by Django 5.2.7 on 2025-10-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_watchlist_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='status',
            field=models.CharField(choices=[('to-watch', 'To Watch'), ('watching', 'Watching'), ('watched', 'Watched'), ('rated', 'Rated')], default='to-watch', max_length=20),
        ),
    ]
